// shared/gallery-client.js
// Lightweight Supabase client for the browser extension.
// No bundler needed — uses the Supabase REST API directly via fetch.
// Store your Supabase URL and anon key in extension storage.

(function () {
  const ext = globalThis.RestyleBrowserApi || globalThis.browser || globalThis.chrome;

  const GALLERY_CONFIG_KEY = "gallery_config";

  async function getConfig() {
    const result = await ext.storage.local.get({ [GALLERY_CONFIG_KEY]: null });
    return result[GALLERY_CONFIG_KEY];
  }

  async function saveConfig(config) {
    await ext.storage.local.set({ [GALLERY_CONFIG_KEY]: config });
  }

  async function ensureConfig() {
    const config = await getConfig();
    if (!config || !config.supabaseUrl || !config.supabaseAnonKey) {
      throw new Error(
        "Gallery not configured. Set your Supabase URL and anon key in the extension options."
      );
    }
    return config;
  }

  async function apiCall(path, options = {}) {
    const config = await ensureConfig();
    const { method = "GET", body, headers = {} } = options;

    const res = await fetch(`${config.supabaseUrl}/rest/v1${path}`, {
      method,
      headers: {
        "apikey": config.supabaseAnonKey,
        "Authorization": `Bearer ${config.accessToken || config.supabaseAnonKey}`,
        "Content-Type": "application/json",
        ...headers,
      },
      body: body ? JSON.stringify(body) : undefined,
    });

    if (!res.ok) {
      const err = await res.json().catch(() => ({ message: res.statusText }));
      throw new Error(err.message || `API error ${res.status}`);
    }

    // 204 No Content
    if (res.status === 204) return null;

    return res.json();
  }

  // ── Auth ─────────────────────────────────────────────

  async function signIn(email, password) {
    const config = await ensureConfig();
    const res = await fetch(`${config.supabaseUrl}/auth/v1/token?grant_type=password`, {
      method: "POST",
      headers: {
        "apikey": config.supabaseAnonKey,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({ email, password }),
    });
    if (!res.ok) {
      const err = await res.json().catch(() => ({ error_description: "Login failed" }));
      throw new Error(err.error_description || "Login failed");
    }
    const data = await res.json();
    config.accessToken = data.access_token;
    config.refreshToken = data.refresh_token;
    config.userId = data.user?.id;
    await saveConfig(config);
    return data;
  }

  async function signOut() {
    const config = await ensureConfig();
    delete config.accessToken;
    delete config.refreshToken;
    delete config.userId;
    await saveConfig(config);
  }

  async function getCurrentUser() {
    try {
      const config = await ensureConfig();
      if (!config.accessToken) return null;
      const data = await apiCall("/profiles?id=eq." + encodeURIComponent(config.userId), {
        headers: { "Accept-Profile": "gallery" },
      });
      return Array.isArray(data) ? data[0] : null;
    } catch {
      return null;
    }
  }

  async function isAuthenticated() {
    const config = await getConfig();
    return !!(config && config.accessToken);
  }

  // ── Styles ───────────────────────────────────────────

  async function uploadStyle(morphixJson, tags) {
    const body = {
      author_id: (await ensureConfig()).userId,
      name: morphixJson.style.name,
      slug: "", // will be generated by the DB function
      description: morphixJson.style.description || "",
      url_pattern: morphixJson.style.url_pattern,
      morphix_file: morphixJson,
      tags: tags || [],
    };

    // Use the upload API endpoint with auth
    const config = await ensureConfig();
    const res = await fetch(`${config.supabaseUrl}/rest/v1/rpc/upload_style`, {
      method: "POST",
      headers: {
        "apikey": config.supabaseAnonKey,
        "Authorization": `Bearer ${config.accessToken}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify(body),
    });

    if (!res.ok) {
      // Fallback: insert directly into styles table
      const insertRes = await fetch(`${config.supabaseUrl}/rest/v1/styles`, {
        method: "POST",
        headers: {
          "apikey": config.supabaseAnonKey,
          "Authorization": `Bearer ${config.accessToken}`,
          "Content-Type": "application/json",
          "Prefer": "return=representation",
        },
        body: JSON.stringify({
          ...body,
          slug: body.name.toLowerCase().replace(/[^a-z0-9]+/g, "-").slice(0, 60),
        }),
      });
      if (!insertRes.ok) {
        const err = await insertRes.json().catch(() => ({ message: "Upload failed" }));
        throw new Error(err.message || "Upload failed");
      }
      return insertRes.json();
    }

    return res.json();
  }

  async function getStylesForSite(domain) {
    const styles = await apiCall(
      `/styles?select=id,name,slug,description,screenshot_urls,avg_rating,installs_count&url_pattern=cs.${encodeURIComponent(JSON.stringify({ type: "domain", value: domain }))}&is_published=eq.true&limit=5`
    );
    return styles || [];
  }

  // ── Exports ──────────────────────────────────────────

  self.MorphixGallery = {
    // Auth
    signIn,
    signOut,
    getCurrentUser,
    isAuthenticated,
    // Config
    getConfig,
    saveConfig,
    // Styles
    uploadStyle,
    getStylesForSite,
  };
})();
