// shared/gallery-client.js
// Lightweight Supabase client for the browser extension.
// No bundler needed — uses the Supabase REST API directly via fetch.
// Supabase URL and anon key are hardcoded — they're public by design.
// Users only need an account (email + password) on the Morphix Gallery.

(function () {
  const ext = globalThis.RestyleBrowserApi || globalThis.browser || globalThis.chrome;

  // Hardcoded Morphix Gallery Supabase config (public anon key)
  const SUPABASE_URL = "https://srmqjagfdedeovkiqpuj.supabase.co";
  const SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNybXFqYWdmZGVkZW92a2lxcHVqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzg1MzE3NzAsImV4cCI6MjA5NDEwNzc3MH0.w_7XjUyRKxGmrc3_Z9qsqj2Dy1lCCDmMV_Z_ILLyg3Q";

  const GALLERY_CONFIG_KEY = "gallery_config";

  async function getConfig() {
    const result = await ext.storage.local.get({ [GALLERY_CONFIG_KEY]: null });
    return result[GALLERY_CONFIG_KEY];
  }

  async function saveConfig(config) {
    await ext.storage.local.set({ [GALLERY_CONFIG_KEY]: config });
  }

  function getSupabaseUrl() {
    return SUPABASE_URL;
  }

  function getSupabaseAnonKey() {
    return SUPABASE_ANON_KEY;
  }

  function ensureConfig() {
    return { supabaseUrl: SUPABASE_URL, supabaseAnonKey: SUPABASE_ANON_KEY };
  }

  async function apiCall(path, options = {}) {
    const config = ensureConfig();
    const { method = "GET", body, headers = {} } = options;
    const token = await getAccessToken();

    const res = await fetch(`${config.supabaseUrl}/rest/v1${path}`, {
      method,
      headers: {
        "apikey": config.supabaseAnonKey,
        "Authorization": `Bearer ${token || config.supabaseAnonKey}`,
        "Content-Type": "application/json",
        ...headers,
      },
      body: body ? JSON.stringify(body) : undefined,
    });

    if (!res.ok) {
      const err = await res.json().catch(() => ({ message: res.statusText }));
      throw new Error(err.message || `API error ${res.status}`);
    }

    // 204 No Content
    if (res.status === 204) return null;

    return res.json();
  }

  // ── Auth ─────────────────────────────────────────────

  async function getAccessToken() {
    const config = await getConfig();
    return config?.accessToken || null;
  }

  async function signIn(email, password) {
    const res = await fetch(`${SUPABASE_URL}/auth/v1/token?grant_type=password`, {
      method: "POST",
      headers: {
        "apikey": SUPABASE_ANON_KEY,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({ email, password }),
    });
    if (!res.ok) {
      const err = await res.json().catch(() => ({ error_description: "Login failed" }));
      throw new Error(err.error_description || "Login failed");
    }
    const data = await res.json();

    // Store only auth tokens, not Supabase config (that's hardcoded now)
    const config = (await getConfig()) || {};
    config.accessToken = data.access_token;
    config.refreshToken = data.refresh_token;
    config.userId = data.user?.id;
    await saveConfig(config);
    return data;
  }

  async function signUp(email, password, username) {
    const res = await fetch(`${SUPABASE_URL}/auth/v1/signup`, {
      method: "POST",
      headers: {
        "apikey": SUPABASE_ANON_KEY,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        email,
        password,
        data: { username, display_name: username },
      }),
    });
    if (!res.ok) {
      const err = await res.json().catch(() => ({ error_description: "Signup failed" }));
      throw new Error(err.error_description || err.msg || "Signup failed");
    }
    return res.json();
  }

  async function signOut() {
    const config = await getConfig();
    if (config) {
      delete config.accessToken;
      delete config.refreshToken;
      delete config.userId;
      await saveConfig(config);
    }
  }

  async function getCurrentUser() {
    try {
      const token = await getAccessToken();
      if (!token) return null;
      const config = await getConfig();
      if (!config?.userId) return null;
      const data = await apiCall("/profiles?id=eq." + encodeURIComponent(config.userId), {
        headers: { "Accept-Profile": "gallery" },
      });
      return Array.isArray(data) ? data[0] : null;
    } catch {
      return null;
    }
  }

  async function isAuthenticated() {
    const token = await getAccessToken();
    return !!token;
  }

  // ── Styles ───────────────────────────────────────────

  async function uploadStyle(morphixJson, tags) {
    const config = await getConfig();
    if (!config?.accessToken) throw new Error("Sign in to share styles.");
    if (!config?.userId) throw new Error("Account setup incomplete. Try signing in again.");

    const body = {
      author_id: config.userId,
      name: morphixJson.style.name,
      slug: "", // will be generated by the DB function
      description: morphixJson.style.description || "",
      url_pattern: morphixJson.style.url_pattern,
      morphix_file: morphixJson,
      tags: tags || [],
    };

    // Use the upload API endpoint with auth
    const res = await fetch(`${SUPABASE_URL}/rest/v1/rpc/upload_style`, {
      method: "POST",
      headers: {
        "apikey": SUPABASE_ANON_KEY,
        "Authorization": `Bearer ${config.accessToken}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify(body),
    });

    if (!res.ok) {
      // Fallback: insert directly into styles table
      const insertRes = await fetch(`${SUPABASE_URL}/rest/v1/styles`, {
        method: "POST",
        headers: {
          "apikey": SUPABASE_ANON_KEY,
          "Authorization": `Bearer ${config.accessToken}`,
          "Content-Type": "application/json",
          "Prefer": "return=representation",
        },
        body: JSON.stringify({
          ...body,
          slug: body.name.toLowerCase().replace(/[^a-z0-9]+/g, "-").slice(0, 60),
        }),
      });
      if (!insertRes.ok) {
        const err = await insertRes.json().catch(() => ({ message: "Upload failed" }));
        throw new Error(err.message || "Upload failed");
      }
      return insertRes.json();
    }

    return res.json();
  }

  async function getStylesForSite(domain) {
    const styles = await apiCall(
      `/styles?select=id,name,slug,description,screenshot_urls,avg_rating,installs_count&url_pattern=cs.${encodeURIComponent(JSON.stringify({ type: "domain", value: domain }))}&is_published=eq.true&limit=5`
    );
    return styles || [];
  }

  // ── Exports ──────────────────────────────────────────

  self.MorphixGallery = {
    // Auth
    signIn,
    signUp,
    signOut,
    getCurrentUser,
    isAuthenticated,
    // Config (read-only for consumers that check config)
    getConfig,
    saveConfig,
    getSupabaseUrl,
    getSupabaseAnonKey,
    // Styles
    uploadStyle,
    getStylesForSite,
  };
})();
